name: CI

on:
  push:
    branches:
      - firehorn/dev/maxime

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt6 dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev-tools qt6-base-dev libqt6svg6-dev libqt5serialport5-dev libgtest-dev

    - name: Install CMake
      run: |
        sudo apt-get install -y cmake

    - name: Configure and build project
      run: |
        cmake -S GUI -B build
        cmake --build build 

    - name: Run tests
      run: |
        cd build
        ./tests/my_tests > test_results.txt

    - name: Append test results to README
      run: |
        echo '\nTest results:' >> README.md
        cat test_results.txt >> README.md
